Repository Dev-FE-2/toy-project1-team4-intranet-project, pull requests merged in 2024-10, with the labels that each got.

#2 [⚙ Setting] 깃허브 이슈 템플릿 추가
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/help.yml
  .github/ISSUE_TEMPLATE/setting.yml
Labels: ⚙ Setting

#6 [Setting] prettier와 eslint 설치 및 설정
  .eslintrc.cjs
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/help.yml
  .github/ISSUE_TEMPLATE/setting.yml
  .gitignore
  .prettier
  README.md
  package-lock.json
  package.json
  server/data/users.json
  server/database.js
  server/index.js
  src/counter.js
  src/main.js
  vite.config.js
Labels: ⚙ Setting

#8 [Fix] package.json eslint 버전 변경
  package.json
Labels: ⚙ Setting

#16 [✨ Feature] 프로젝트 페이지 레이아웃 생성과 스타일 정의
  index.html
  public/logo.svg
  public/vite.svg
  src/assets/avatar.svg
  src/assets/icons/icon_employee.svg
  src/assets/icons/icon_home.svg
  src/assets/icons/icon_notice.svg
  src/assets/icons/icon_profile.svg
  src/assets/icons/icon_timetable.svg
  src/global.css
  src/javascript.svg
  src/layout.js
  src/main.js
  src/pages/sample/index.html
  src/pages/sample/index.js
  src/reset.css
  src/style.css
Labels: ✨ Feature, 🎨 Design

#18 [✨ Feature] 모바일 반응형 레이아웃
  public/avatar.svg
  public/logo.svg
  src/components/Icon/IconEmployee.js
  src/components/Icon/IconHome.js
  src/components/Icon/IconNotice.js
  src/components/Icon/IconProfile.js
  src/components/Icon/IconTimetable.js
  src/components/Icon/index.js
  src/components/Layout/DeskTopLayout/index.js
  src/components/Layout/DeskTopLayout/style.css
  src/components/Layout/MobileLayout/index.js
  src/components/Layout/MobileLayout/style.css
  src/components/Layout/Navigation/index.js
  src/components/Layout/Navigation/style.css
  src/components/Layout/index.js
  src/global.css
  src/layout.js
  src/main.js
  src/pages/sample/index.html
  src/pages/sample/index.js
  src/reset.css
Labels: ✨ Feature, 🎨 Design

#24 [✨Feature] 개인/ 직원 프로필, 직원 리스트 페이지 마크업
  server/data/employees.js
  server/data/user.js
  src/components/Layout/MobileLayout/index.js
  src/components/pages/Profile/ProfileForm.js
  src/components/pages/Profile/ProfileImage.js
  src/pages/EmployeeAdd/index.js
  src/pages/EmployeeAdd/style.css
  src/pages/EmployeeDetail/index.js
  src/pages/EmployeeDetail/style.css
  src/pages/EmployeeList/index.js
  src/pages/EmployeeList/style.css
  src/pages/userProfile/index.js
  src/pages/userProfile/style.css
Labels: 🎨 Design

#25 [✨ Feature] 근태 관리 페이지 반응형 UI 구현
  src/pages/vacation/index.js
  src/pages/vacation/style.css
Labels: 🎨 Design

#26 [✨ Feature] 공지사항 페이지 UI 구현
  src/assets/icons/icon_search.svg
  src/pages/notice/index.js
  src/pages/notice/style.css
  src/pages/noticeDetail/index.js
  src/pages/noticeDetail/style.css
Labels: 🎨 Design

#27 [✨Feature] 마이페이지 화면 구현
  src/pages/mypage/index.js
  src/pages/mypage/style.css
Labels: ✨ Feature, 🎨 Design

#28 [✨ Feature] 라우트 구현과 클래스 컴포넌트로 전환, 404 not found 페이지 생성
  src/assets/404.png
  src/components/Layout/DeskTopLayout/index.js
  src/components/Layout/MobileLayout/index.js
  src/components/Layout/Navigation/index.js
  src/components/Layout/index.js
  src/global.css
  src/main.js
  src/pages/index.js
  src/pages/login/index.js
  src/pages/notFound/index.js
  src/pages/notFound/style.css
  src/pages/sample/index.html
  src/pages/sample/index.js
  src/router/pages.js
  src/router/route.js
  src/router/url.js
Labels: ✨ Feature, 🎨 Design

#31 [✨Feature] 개인/ 직원 프로필, 직원 리스트 페이지 수정
  src/components/pages/Profile/ProfileForm.js
  src/components/pages/Profile/ProfileImage.js
  src/global.css
  src/pages/EmployeeAdd/index.js
  src/pages/EmployeeAdd/style.css
  src/pages/EmployeeDetail/index.js
  src/pages/EmployeeDetail/style.css
  src/pages/EmployeeList/index.js
  src/pages/EmployeeList/style.css
  src/pages/userProfile/index.js
  src/pages/userProfile/style.css
Labels: 🎨 Design

#35 [🔨 Fix] CSS 스타일링 이슈 및 경로 이슈 수정
  src/components/Layout/DeskTopLayout/index.js
  src/components/Layout/MobileLayout/index.js
  src/components/Layout/Navigation/style.css
  src/global.css
  src/router/route.js
Labels: 🎨 Design, 🔨 Fix

#38 [🔨 Fix] 라우터 URL 접근 이슈 수정
  src/components/Layout/DeskTopLayout/index.js
  src/components/Layout/MobileLayout/index.js
  src/main.js
  src/pages/notFound/index.js
  src/router/pages.js
  src/router/route.js
Labels: 🔨 Fix

#40 [🔨 Fix] prettier 포맷팅 모든 파일에서 JS로만 변경
  package.json
Labels: ⚙ Setting, 🔨 Fix

#43 [✨ Feature] 마이페이지 타이머 구현
  src/pages/mypage/index.js
  src/router/pages.js
  src/router/route.js
Labels: ✨ Feature

#47 [🐞 Bug] 메인페이지(마이페이지)에서 다른 페이지로 이동시 MyPage.updateCurrentTime 오류가 생김
  src/pages/mypage/index.js
Labels: 🐞 BugFix

#48 [✨ Feature] 프로필 페이지 이미지업로드
  src/pages/EmployeeAdd/index.js
  src/pages/EmployeeAdd/style.css
  src/pages/EmployeeDetail/index.js
  src/pages/EmployeeDetail/style.css
  src/pages/EmployeeList/index.js
  src/pages/userProfile/index.js
  src/pages/userProfile/style.css
Labels: ✨ Feature

#52 [🔨 Fix] 모바일 레이아웃 페이지와 네비게이션 동작하지 않은 이슈
  src/components/Layout/DeskTopLayout/index.js
  src/components/Layout/DeskTopLayout/style.css
  src/components/Layout/MobileLayout/index.js
  src/components/Layout/MobileLayout/style.css
  src/components/Layout/UserStatus/index.js
  src/components/Layout/UserStatus/style.css
  src/components/Layout/index.js
  src/components/Layout/style.css
  src/main.js
  src/pages/EmployeeDetail/style.css
  src/pages/EmployeeList/style.css
  src/pages/userProfile/style.css
  src/pages/vacation/index.js
  src/router/pages.js
  src/router/route.js
  src/router/url.js
Labels: 🔨 Fix

#51 [✨ Feature] 마이페이지 모달창 및 근무 시간 기능구현
  src/pages/mypage/index.js
  src/pages/mypage/modal.js
  src/pages/mypage/style.css
Labels: ✨ Feature, 🎨 Design

#59 [✨ Feature] 근태 신청 페이지 및 모달 창 버튼 이벤트 추가
  src/pages/vacation/VacationApplyModal.js
  src/pages/vacation/VacationHistoryModal.js
  src/pages/vacation/index.js
  src/pages/vacation/style.css
  src/router/route.js
Labels: ✨ Feature

#61 [⚙ Setting] mockup API msw 셋업
  package-lock.json
  package.json
  public/mockServiceWorker.js
  server/data/employees.js
  server/data/index.js
  server/data/sample.js
  server/data/vacation.js
  src/main.js
  src/mocks/browser.js
  src/mocks/handlers.js
  src/mocks/node.js
  src/pages/sample/index.js
  src/router/route.js
  vite.config.js
Labels: ⚙ Setting

#57 [✨ Feature] 마이페이지 프로필 정보 가져오기
  src/pages/mypage/index.js
  src/pages/mypage/modal.js
  src/pages/mypage/profile/userProfile.js
  src/pages/mypage/profile/userProfileData.json
  src/pages/mypage/style.css
Labels: ✨ Feature, 🎨 Design

#64 [🔨 Fix] 마이페이지 json 파일 이름 변경으로 인한 오류 수정
  src/pages/mypage/profile/userProfile.js
Labels: 🔨 Fix

#66 [✨ Feature] 근태 신청 페이지 submit시 데이터 전송 기능 추가 #62
  server/data/vacation.js
  src/mocks/handlers.js
  src/pages/vacation/VacationApplyModal.js
  src/pages/vacation/index.js
Labels: ✨ Feature, 🔨 Fix

#68 [🔨 Fix] vacation.js 내부 파일 데이터 변경
  server/data/vacation.js
Labels: 🔨 Fix

#71 [✨ Feature] 직원 휴가 리스트와 필터링 기능 구현
  src/pages/vacation/components/Pagination.js
  src/pages/vacation/components/VacationListItem.js
  src/pages/vacation/index.js
  src/pages/vacation/style.css
Labels: ✨ Feature

#69 [✨ Feature] 공지사항 페이지 스크롤 기능 등 추가
  src/pages/notice/index.js
  src/pages/notice/noticeList.js
  src/pages/notice/style.css
Labels: ✨ Feature

#70 [✨ Feature] 마이페이지 근태 신청 리스트 프리뷰
  src/pages/mypage/index.js
  src/pages/mypage/previewAttendance.js
  src/pages/mypage/profile/userProfile.js
  src/pages/mypage/profile/userProfileData.json
Labels: ✨ Feature

#72 [✨ Feature] 직원 목록 페이지 기능 구현
  server/data/employees.js
  server/data/user.js
  src/components/pages/Profile/ProfileForm.js
  src/mocks/handlers.js
  src/pages/EmployeeAdd/index.js
  src/pages/EmployeeAdd/style.css
  src/pages/EmployeeDetail/index.js
  src/pages/EmployeeDetail/style.css
  src/pages/EmployeeList/index.js
  src/pages/EmployeeList/style.css
  src/pages/userProfile/index.js
  src/pages/userProfile/style.css
Labels: ✨ Feature
