Repository Dev-FE-2/toy-project1-team4-intranet-project, pull requests merged in 2024-11, with the labels that each got.

#75 [✨ Feature] 근태 신청 페이지 신청 내역 모달 구현 #74
  src/mocks/handlers.js
  src/pages/vacation/VacationApplyModal.js
  src/pages/vacation/VacationHistoryModal.js
  src/pages/vacation/components/VacationListItem.js
  src/pages/vacation/index.js
  src/pages/vacation/style.css
Labels: ✨ Feature

#79 fix: 근태 신청 폼 제출 시 결과 alert 출력 및 근태 신청 컴포넌트 파일 폴더 분리
  src/pages/vacation/components/VacationApplyModal.js
  src/pages/vacation/components/VacationHistoryModal.js
  src/pages/vacation/components/VacationListItem.js
  src/pages/vacation/index.js
Labels: 🔨 Fix

#78 [✨ Feature] 근태 내역 조회 휴가 타입별 필터링
  .eslintrc.cjs
  package-lock.json
  server/data/user.js
  server/data/vacation.js
  src/pages/vacation/components/Pagination.js
  src/pages/vacation/components/VacationListItem.js
  src/pages/vacation/components/VacationTypeTabMenu.js
  src/pages/vacation/index.js
Labels: ✨ Feature

#81 docs: readme 문서작업 1차
  README.md
Labels: 📃 Docs

#86 [🔨 Fix] 중복 코드 제거와 근태신청 페이지 관련 컴포넌트 파일 이동
  src/components/pages/Vacation/Pagination.js
  src/components/pages/Vacation/VacationApplyModal.js
  src/components/pages/Vacation/VacationHistoryModal.js
  src/components/pages/Vacation/VacationListItem.js
  src/components/pages/Vacation/VacationTypeTabMenu.js
  src/components/pages/Vacation/index.js
  src/pages/vacation/index.js
Labels: 🔨 Fix

#82 [✨ Feature] 마이페이지 근무 신청 페이지 라우팅
  src/pages/mypage/index.js
Labels: ✨ Feature

#88 [📃 Docs] Readme.md 및 프로젝트 관련 문서 작성 - 2차
  README.md
Labels: 📃 Docs

#97 [⚙ Setting] 리팩토링 이슈 템플릿 추가
  .github/ISSUE_TEMPLATE/refactor.yml
Labels: ⚙ Setting

#100 [✨ Feature] 공지사항 페이지 검색기능 추가 #54
  src/pages/notice/index.js
  src/pages/notice/style.css
Labels: ✨ Feature

#103 [🔨 Refactor] 일관성을 위한 경로 및 파일 컨벤션 카멜케이스로 수정
  src/components/Icon/index.js
  src/components/Layout/Navigation/index.js
  src/components/Layout/index.js
  src/components/icon/iconEmployee.js
  src/components/icon/iconHome.js
  src/components/icon/iconNotice.js
  src/components/icon/iconProfile.js
  src/components/icon/iconTimetable.js
  src/components/icon/index.js
  src/components/pages/Vacation/index.js
  src/components/pages/profile/profileForm.js
  src/components/pages/profile/profileImage.js
  src/components/pages/vacation/index.js
  src/components/pages/vacation/pagination.js
  src/components/pages/vacation/vacationApplyModal.js
  src/components/pages/vacation/vacationHistoryModal.js
  src/components/pages/vacation/vacationListItem.js
  src/components/pages/vacation/vacationTypeTabMenu.js
  src/counter.js
  src/main.js
  src/pages/employeeAdd/index.js
  src/pages/employeeAdd/style.css
  src/pages/employeeDetail/index.js
  src/pages/employeeDetail/style.css
  src/pages/employeeList/index.js
  src/pages/employeeList/style.css
  src/pages/index.js
  src/pages/sample/index.html
  src/pages/userProfile/index.js
  src/pages/vacation/index.js
  src/router/route.js
Labels: 🔨 Refactor

#108 [🐞 Bug] Layout 관련 파일명 대소문자 변경이 적용되지 않은 이슈 해결
  src/components/layout/index.js
  src/components/layout/navigation/index.js
  src/components/layout/navigation/style.css
  src/components/layout/style.css
  src/components/layout/userStatus/index.js
  src/components/layout/userStatus/style.css
Labels: 🐞 BugFix

#109 [🔨 Refactor] 함수형 리턴 형태의 컴포넌트를 클래스형 컴포넌트 형태로 일관성 있게 수정
  src/components/icon/iconEmployee.js
  src/components/icon/iconHome.js
  src/components/icon/iconNotice.js
  src/components/icon/iconProfile.js
  src/components/icon/iconTimetable.js
  src/components/layout/navigation/index.js
Labels: 🔨 Refactor

#111 [✨ Feature] 로딩, no data, 서버 에러 UI 컴포넌트 생성과 근태(휴가) 신청 리스트 조회 에러 핸들링
  src/assets/503.jpg
  src/assets/503.svg
  src/assets/no-data.jpg
  src/assets/no-data.svg
  src/components/common/error503/index.js
  src/components/common/index.js
  src/components/common/loading/index.js
  src/components/common/loading/style.css
  src/components/common/noData/index.js
  src/components/common/style.css
  src/components/pages/vacation/vacationListItem.js
  src/global.css
  src/reset.css
Labels: ✨ Feature

#114 [✨ Feature] 이미지 업로드를 위한 multer 추가 및 샘플 코드 작성
  package-lock.json
  package.json
  server.cjs
  server/api/noticeApi.cjs
  server/api/userApi.cjs
  server/api/userProfileApi.cjs
  server/api/vacationApi.cjs
  src/pages/mypage/index.js
Labels: ✨ Feature

#115 [🔨 Refactor] 근태(휴가) 신청 관련 class 필드와 메서드의 private 접근제어자를 적용하여 캡슐화와 공통 함수 모듈화
  .eslintrc.cjs
  src/apis/index.js
  src/apis/mypageApi.js
  src/apis/noticeApi.js
  src/apis/userProfileApi.js
  src/apis/vacationApi.js
  src/components/pages/vacation/pagination.js
  src/components/pages/vacation/vacationListItem.js
  src/components/pages/vacation/vacationTypeTabMenu.js
  src/utils/loadingUtil.js
Labels: 🔨 Refactor

#117 refactor: 근태 신청 모달 생성자 함수 내부 변수명 변경 및 폼 제출 이벤트리스너 콜백 함수 스타일 변경
  src/components/pages/vacation/vacationApplyModal.js
Labels: 🔨 Refactor

#119 [🔨 Refactor] 근태 내역 모달 내부 중복되는 로직 수정 및 변수명 직관성있게 변경 (#118)
  src/components/pages/vacation/vacationHistoryModal.js
Labels: 🔨 Refactor

#121 [✨ Feature] 회원가입 기능 구현
  server.cjs
  server/api/userApi.cjs
  src/apis/index.js
  src/apis/userApi.js
  src/apis/userProfileApi.js
  src/components/common/error503/index.js
  src/components/common/form/index.js
  src/components/common/form/input.js
  src/components/common/style.css
  src/components/pages/vacation/vacationListItem.js
  src/global.css
  src/pages/index.js
  src/pages/login/formFields.js
  src/pages/login/index.js
  src/pages/notFound/style.css
  src/pages/signup/formFields.js
  src/pages/signup/index.js
  src/router/route.js
  src/router/url.js
Labels: ✨ Feature

#126 [🔨 Refactor] 공지사항 페이지 컴포넌트 분리 및 데이터 통신 기능 추가
  server/api/noticeApi.cjs
  src/apis/noticeApi.js
  src/components/pages/notice/infiniteScroll.js
  src/components/pages/notice/pagination.css
  src/components/pages/notice/pagination.js
  src/components/pages/notice/search.css
  src/components/pages/notice/search.js
  src/pages/notice/index.js
  src/pages/notice/style.css
  src/pages/noticeDetail/index.js
  src/pages/noticeDetail/style.css
Labels: 🔨 Refactor

#128 [🐞 Bug] 클래스명 대분자로 변경 후 import 변경 안함으로 인한 버그
  src/pages/employeeAdd/index.js
  src/pages/employeeDetail/index.js
  src/pages/userProfile/index.js
Labels: 🐞 BugFix

#130 [🔨 Refactor] Form을 재사용 가능하도록 Button 컴포넌트 생성 및 분리
  src/components/common/error/error404.js
  src/components/common/error/error503.js
  src/components/common/error/index.js
  src/components/common/error503/index.js
  src/components/common/form/button.js
  src/components/common/form/buttonGroup.js
  src/components/common/form/form.js
  src/components/common/form/index.js
  src/components/common/index.js
  src/components/common/style.css
  src/pages/login/formFieldDatas.js
  src/pages/login/index.js
  src/pages/notFound/index.js
  src/pages/notFound/style.css
  src/pages/signup/formFieldDatas.js
  src/pages/signup/index.js
  src/router/route.js
Labels: 🔨 Refactor

#132 [⚙ Setting] .gitignore 파일에 database.sqlite 추가
  .gitignore
Labels: ⚙ Setting

#134 [🔨 Fix] 백엔드 요청 엔드포인트 공통 속성으로 변경 및 PROD config 추가
  config.js
  src/pages/mypage/index.js
Labels: 🔨 Fix

#135 [✨ Feature] 마이페이지 이번 주 근무시간 영역 기능 추가
  database.sqlite
  server/api/mypageApi.cjs
  src/pages/mypage/index.js
  src/pages/mypage/style.css
  src/pages/mypage/workStatus.js
Labels: ✨ Feature

#141 [🐞 Bug] router 상태관리자를 생성되기 전에 import 해서 에러가 나는 이슈 수정
  src/components/layout/layout/index.js
Labels: 🐞 BugFix

#142 [🔨 Fix] router 전역 상태 관리자 생성하여 레이아웃 링크 관련 이슈 해결과 네비게이션의 프로필 메뉴 링크 동적으로 연결
  src/components/common/form/form.js
  src/components/layout/layout/index.js
  src/components/layout/loginStatus/index.js
  src/components/layout/navigation/index.js
  src/components/layout/navigation/navListData.js
  src/pages/login/index.js
  src/router/navigate.js
  src/router/route.js
  src/router/url.js
  src/services/auth/index.js
  src/store/authManager.js
  src/store/index.js
  src/store/routerManager.js
Labels: 🐞 BugFix, 🔨 Refactor, 🔨 Fix
